### ISSUE TITLE
RVIZ segfaults when loading herb.urdf

### ISSUE THREAD

**Issue by mklingen** [personalrobotics/herb_description#4]
One of the STL files is apparently wrong. Replacing collision STLs with daes magically fixes the segfault.

**Comment by mklingen** [comment]
@mkoval any update on this? My collision meshes are still all high poly daes...

**Comment by mkoval** [comment]
I've narrowed this down to the `head_wam2_collision.STL` mesh. The model successfully loads if you remove that single mesh.
