### ISSUE TITLE
Right hand has mismatch in collision and visual joints after building

### ISSUE THREAD

**Issue by gilwoolee** [personalrobotics/herb_description#56]
I noticed that in the built urdf file (herb.urdf), the right hand collision origins are not copied from bh282.urdf.xacro and thus the visual and collision meshes do not match. This may be due to the processing script we have.

**Comment by brianhou** [comment]
Just to be a little bit more specific, it seems that `<origin>` tags nested inside `<collision>` tags in the hand aren't being copied. `herb_base.urdf.xacro` specifies some of these as well, which _are_ copied into the built `herb.urdf`. The built `bh280.urdf` is also missing these nested `<origin>` tags, so it doesn't seem like it's just some issue with includes.

**Comment by brianhou** [comment]
On second glance, it seems that this sometimes works? I ran `catkin clean` and rebuilt `herb_description`, and it seems to be there. However, I think the artifacts from the previous build that informed my previous comment were also from current `master`. The mystery continues.

**Comment by gilwoolee** [comment]
Ohhh yeah catkin clean fixed it for me too. I'll just close it for now
